# Generated by Django 6.0.1 on 2026-02-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
